name: JailX
main: TStark\JailX\Main
<<<<<<< HEAD
version: 2.0.0
api: 5.0.0
author: §bT. Stark
description: §6Un plugin para administrar una cárcel en el servidor.
website: §ahttps://mcpetools.surge.sh

commands:
=======
version: 1.0.0
api: 5.0.0
author: §bT. Stark
description: §6A plugin to manage a jail on the server.
website: §ahttps://mcpetools.surge.sh

commands:
  jail:
    description: "Arrest a suspicious player"
    usage: "/jail <nick>"
    permission: "jailx.command.jail"
>>>>>>> ae39fb60dc4cc788647dcd7f972ac58c7b0f241d
  setjail:
    description: "Set the position of the jail"
    usage: "/setjail"
    permission: "jailx.command.setjail"
  jail:
    description: "Arresta a un jugador sospechoso"
    usage: "/jail <nick> [duration]"
    permission: "jailx.command.jail"
  unjail:
<<<<<<< HEAD
    description: "Libera a un jugador de la cárcel"
    usage: "/unjail <nick>"
=======
    description: "Release a player from jail"
    usage: "/unjail <player>"
>>>>>>> ae39fb60dc4cc788647dcd7f972ac58c7b0f241d
    permission: "jailx.command.unjail"
  jaillist:
    description: "Lista a los jugadores en la cárcel"
    usage: "/jaillist"
    permission: "jailx.command.jaillist"
  jailstatus:
    description: "Muestra el estado de un jugador en la cárcel"
    usage: "/jailstatus <nick>"
    permission: "jailx.command.jailstatus"

permissions:
<<<<<<< HEAD
  jailx.command.setjail:
    default: op
    description: Permite establecer la posición de la cárcel.
  jailx.command.jail:
    default: op
    description: Permite arrestar a un jugador sospechoso.
  jailx.command.unjail:
    default: op
    description: Permite liberar a un jugador de la cárcel.
  jailx.command.jaillist:
    default: op
    description: Muestra la lista de los jugadores en la cárcel.
  jailx.command.jailstatus:
    default: op
    description: Muestra el estado de un jugador en la cárcel.
=======
  jailx.command.jail:
    default: op
    description: Allows you to arrest a suspicious player.
  jailx.command.setjail:
    default: op
    description: Allows you to set the position of the jail.
  jailx.command.unjail:
    default: op
    description: Allows you to free a player from jail.
>>>>>>> ae39fb60dc4cc788647dcd7f972ac58c7b0f241d
