# JailX Configuration
jail-message: "§cYou have been sent to jail!"
unjail-message: "§aYou have been released from jail!"
welcome-message: "§eWelcome to jail"
welcome-subtitle: "§6Luck in your stay"

# Jail position
jail-position:
  x: 0
  y: 0
  z: 0
  level: "world"
