# Configuración de JailX
# Developed By: T. Stark

jail-message: "§cYou have been sent to jail!"
unjail-message: "§aYou have been released from jail!"
welcome-message: "§eWelcome to jail"
welcome-subtitle: "§6Good luck during your stay"
jail-position:
  x: 0
  y: 0
  z: 0
  level: "world"
blocked-commands:
  - "hub"
  - "spawn"
  - "lobby"
  - "tp"
  - "tpa"
  - "warp"
  - "wild"
  - "home"
  - "f home"