<<<<<<< HEAD
# Configuración de JailX
# Developed By: T. Stark

jail-message: "§cYou have been sent to jail!"
unjail-message: "§aYou have been released from jail!"
welcome-message: "§eWelcome to jail"
welcome-subtitle: "§6Good luck during your stay"
=======
# JailX Configuration
jail-message: "§cYou have been sent to jail!"
unjail-message: "§aYou have been released from jail!"
welcome-message: "§eWelcome to jail"
welcome-subtitle: "§6Luck in your stay"

# Jail position
>>>>>>> ae39fb60dc4cc788647dcd7f972ac58c7b0f241d
jail-position:
  x: 0
  y: 0
  z: 0
  level: "world"
blocked-commands:
  - "hub"
  - "spawn"
  - "lobby"
  - "tp"
  - "tpa"
  - "warp"
  - "wild"
  - "home"
  - "f home"